/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebasseries;

/**
 *
 * @author jorge
 */
public class PruebaCorridas extends javax.swing.JDialog {

    /**
     * Creates new form PruebaCorridas
     */
    public PruebaCorridas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbln1 = new javax.swing.JLabel();
        lbln2 = new javax.swing.JLabel();
        lblPromedio = new javax.swing.JLabel();
        lblDesviacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblH = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        lblZ = new javax.swing.JLabel();
        lblAceptacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textSerie = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textBinario = new javax.swing.JTextArea();
        lblCorrida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbln1.setText(".");

        lbln2.setText(".");

        lblPromedio.setText(".");

        lblDesviacion.setText(".");

        jLabel1.setText("Serie");

        lblH.setText(".");

        btnGenerar.setText("Mostrar Serie");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        lblZ.setText(".");

        lblAceptacion.setText(".");

        textSerie.setColumns(20);
        textSerie.setRows(5);
        jScrollPane1.setViewportView(textSerie);

        jLabel2.setText("Valores Binarios");

        textBinario.setColumns(20);
        textBinario.setRows(5);
        jScrollPane2.setViewportView(textBinario);

        lblCorrida.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCorrida)
                            .addComponent(lbln1)
                            .addComponent(lbln2)
                            .addComponent(lblPromedio)
                            .addComponent(lblDesviacion)
                            .addComponent(lblH)
                            .addComponent(lblZ)
                            .addComponent(lblAceptacion))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addComponent(btnGenerar)
                        .addGap(117, 117, 117))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGenerar)
                .addGap(29, 29, 29)
                .addComponent(lblCorrida)
                .addGap(18, 18, 18)
                .addComponent(lbln1)
                .addGap(18, 18, 18)
                .addComponent(lbln2)
                .addGap(18, 18, 18)
                .addComponent(lblPromedio)
                .addGap(18, 18, 18)
                .addComponent(lblDesviacion)
                .addGap(18, 18, 18)
                .addComponent(lblH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblZ)
                .addGap(18, 18, 18)
                .addComponent(lblAceptacion)
                .addGap(0, 166, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed

        Double[] vector=new Double[100];
        vector[0]=0.03991;
        vector[1]=0.38555;
        vector[2]=0.17546;
        vector[3]=0.32643;
        vector[4]=0.69572;
        vector[5]=0.24122;
        vector[6]=0.61196;
        vector[7]=0.30532;
        vector[8]=0.03788;
        vector[9]=0.48228;
        vector[10]=0.88618;
        vector[11]=0.71299;
        vector[12]=0.27954;
        vector[13]=0.80863;
        vector[14]=0.33564;
        vector[15]=0.90899;
        vector[16]=0.78038;
        vector[17]=0.55986;
        vector[18]=0.87539;
        vector[19]=0.16818;
        vector[20]=0.10461;
        vector[21]=0.95554;
        vector[22]=0.73704;
        vector[23]=0.52861;
        vector[24]=0.68777;
        vector[25]=0.66591;
        vector[26]=0.30231;
        vector[27]=0.21704;
        vector[28]=0.97599;
        vector[29]=0.63379;
        vector[30]=0.19161;
        vector[31]=0.23853;
        vector[32]=0.58909;
        vector[33]=0.00514;
        vector[34]=0.60780;
        vector[35]=0.75754;
        vector[36]=0.70267;
        vector[37]=0.66485;
        vector[38]=0.08823;
        vector[39]=0.60311;
        vector[40]=0.93716;
        vector[41]=0.32886;
        vector[42]=0.92052;
        vector[43]=0.95819;
        vector[44]=0.39510;
        vector[45]=0.27699;
        vector[46]=0.92962;
        vector[47]=0.10274;
        vector[48]=0.75867;
        vector[49]=0.85783;
        vector[50]=0.41290;
        vector[51]=0.05870;
        vector[52]=0.82444;
        vector[53]=0.20247;
        vector[54]=0.48460;
        vector[55]=0.60833;
        vector[56]=0.43529;
        vector[57]=0.88722;
        vector[58]=0.94813;
        vector[59]=0.74457;
        vector[60]=0.16894;
        vector[61]=0.59780;
        vector[62]=0.46215;
        vector[63]=0.06831;
        vector[64]=0.35905;
        vector[65]=0.06494;
        vector[66]=0.61773;
        vector[67]=0.12202;
        vector[68]=0.20717;
        vector[69]=0.47619;
        vector[70]=0.63312;
        vector[71]=0.01119;
        vector[72]=0.99005;
        vector[73]=0.81759;
        vector[74]=0.85558;
        vector[75]=0.25983;
        vector[76]=0.06318;
        vector[77]=0.56736;
        vector[78]=0.31900;
        vector[79]=0.90561;
        vector[80]=0.98953;
        vector[81]=0.09958;
        vector[82]=0.15917;
        vector[83]=0.19640;
        vector[84]=0.85244;
        vector[85]=0.03152;
        vector[86]=0.22109;
        vector[87]=0.94205;
        vector[88]=0.82037;
        vector[89]=0.87481;
        vector[90]=0.71857;
        vector[91]=0.92784;
        vector[92]=0.04921;
        vector[93]=0.45197;
        vector[94]=0.15191;
        vector[95]=0.01291;
        vector[96]=0.38384;
        vector[97]=0.66164;
        vector[98]=0.54155;
        vector[99]=0.72848;

        String texto1= "";
        for (int i=0; i<vector.length; i++){
            texto1+=vector[i]+"\n";
        }
        textSerie.setText(texto1);

        String texto2= "";
        int[] vectorBinario=new int[100];
        for (int i=0; i<vector.length; i++){
            if(vector[i]>0.5){
                vectorBinario[i]=1;
                texto2+=vectorBinario[i]+"\n";
            }else{
                vectorBinario[i]=0;
                texto2+=vectorBinario[i]+"\n";
            }
        }
        textBinario.setText(texto2);

        int n1=0;
        int n2=0;
        int compara=2;
        int corrida=0;
        //        for (int i=0; i<vectorBinario.length; i++){
            //            if(vectorBinario[i]==0){
                //                if(compara!=0){
                    //                    n1++;
                    //                    compara=vectorBinario[i];
                    //                }
                //            }else{
                //                if(compara!=1){
                    //                    n2++;
                    //                    compara=vectorBinario[i];
                    //                }
                //            }
            //        }
        for (int i=0; i<vectorBinario.length; i++){
            if(vectorBinario[i]!=compara){
                corrida++;
                compara=vectorBinario[i];
            }
        }
        System.out.println("corrida"+corrida);
        lblCorrida.setText("numero de corrida R: "+corrida);
        for (int i=0; i<vectorBinario.length; i++){
            if(vectorBinario[i]==0){
                n1++;
            }else{
                n2++;
            }
        }
        System.out.println("n1:"+n1+"n2:"+n2);
        lbln1.setText("n1: "+n1);
        lbln2.setText("n2: "+n2);

        double num1=(double)n1;
        double num2=(double)n2;
        double promedio=((2*num1*num2)/(num1+num2))+1;
        System.out.println("promedio:"+promedio);
        lblPromedio.setText("promedio Xr: "+promedio);

        double desviacion= Math.sqrt(((2*num1*num2)*((2*num1*num2)-num1-num2))/((Math.pow((num1+num2), 2))*(num1+num2-1)));
        System.out.println("desviacion:"+desviacion);
        lblDesviacion.setText("desviacion Sr: "+desviacion);

        double valor=0;
        double h=0;
        //valor=((2*n1*n2)/(n1+n2))+1;

        if(corrida<promedio){
            h=+0.5;
        }else{
            h=-0.5;
        }
        System.out.println("h:"+h);
        lblH.setText("valor H: "+h);
        double z=0;
        z=(corrida+h-promedio)/(desviacion);
        System.out.println("estadistico aproximacion:"+z);
        lblZ.setText("estadistico aproximacion Zo: "+z);

        if(z>-2.58 &&z<2.58){
            System.out.println("la Z cae en el nivel de aceptacion que es igual a 2.58:"+z);
            lblAceptacion.setText("la Z cae en el nivel de aceptacion que es igual a 2.58:"+z);
        }else{
            System.out.println("la Z no cae en el nivel de aceptacion que es igual a 2.58:"+z);
            lblAceptacion.setText("la Z no cae en el nivel de aceptacion que es igual a 2.58:"+z);

        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaCorridas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaCorridas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaCorridas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaCorridas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PruebaCorridas dialog = new PruebaCorridas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAceptacion;
    private javax.swing.JLabel lblCorrida;
    private javax.swing.JLabel lblDesviacion;
    private javax.swing.JLabel lblH;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblZ;
    private javax.swing.JLabel lbln1;
    private javax.swing.JLabel lbln2;
    private javax.swing.JTextArea textBinario;
    private javax.swing.JTextArea textSerie;
    // End of variables declaration//GEN-END:variables
}
