/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebasseries;

/**
 *
 * @author jorge
 */
public class PruebaPocker extends javax.swing.JDialog {

    /**
     * Creates new form PruebaPocker
     */
    public PruebaPocker(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblest4 = new javax.swing.JLabel();
        lblest5 = new javax.swing.JLabel();
        lblest1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSumaE = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        lblCondicion = new javax.swing.JLabel();
        lblAceptacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textSerie = new javax.swing.JTextArea();
        lblest2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblest3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textBinario = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblest4.setText(".");

        lblest5.setText(".");

        lblest1.setText(".");

        jLabel1.setText("Serie");

        lblSumaE.setText(".");

        btnGenerar.setText("Mostrar Serie");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        lblCondicion.setText(".");

        lblAceptacion.setText(".");

        textSerie.setColumns(20);
        textSerie.setRows(5);
        jScrollPane1.setViewportView(textSerie);

        lblest2.setText(".");

        jLabel2.setText("Casos Poker");

        lblest3.setText(".");

        textBinario.setColumns(20);
        textBinario.setRows(5);
        jScrollPane2.setViewportView(textBinario);

        jLabel3.setText("Caso 1: Todos diferentes, Caso 2: Un par, Caso 3: Dos pares");

        jLabel4.setText("Caso 4: Tercia, Caso 5: Poker");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblest1)
                            .addComponent(lblest2)
                            .addComponent(lblest3)
                            .addComponent(lblest4)
                            .addComponent(lblest5)
                            .addComponent(lblSumaE)
                            .addComponent(lblCondicion)
                            .addComponent(lblAceptacion)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                        .addComponent(btnGenerar)
                        .addGap(117, 117, 117))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGenerar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(8, 8, 8)
                        .addComponent(lblest1)
                        .addGap(18, 18, 18)
                        .addComponent(lblest2)
                        .addGap(18, 18, 18)
                        .addComponent(lblest3)
                        .addGap(18, 18, 18)
                        .addComponent(lblest4)
                        .addGap(18, 18, 18)
                        .addComponent(lblest5)
                        .addGap(18, 18, 18)
                        .addComponent(lblSumaE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCondicion)
                        .addGap(18, 18, 18)
                        .addComponent(lblAceptacion)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed

        String[] vector=new String[100];
        vector[0]="0.03991";
        vector[1]="0.38555";
        vector[2]="0.17546";
        vector[3]="0.32643";
        vector[4]="0.69572";
        vector[5]="0.24122";
        vector[6]="0.61196";
        vector[7]="0.30532";
        vector[8]="0.03788";
        vector[9]="0.48228";
        vector[10]="0.88618";
        vector[11]="0.71299";
        vector[12]="0.27954";
        vector[13]="0.80863";
        vector[14]="0.33564";
        vector[15]="0.90899";
        vector[16]="0.78038";
        vector[17]="0.55986";
        vector[18]="0.87539";
        vector[19]="0.16818";
        vector[20]="0.10461";
        vector[21]="0.95554";
        vector[22]="0.73704";
        vector[23]="0.52861";
        vector[24]="0.68777";
        vector[25]="0.66591";
        vector[26]="0.30231";
        vector[27]="0.21704";
        vector[28]="0.97599";
        vector[29]="0.63379";
        vector[30]="0.19161";
        vector[31]="0.23853";
        vector[32]="0.58909";
        vector[33]="0.00514";
        vector[34]="0.60780";
        vector[35]="0.75754";
        vector[36]="0.70267";
        vector[37]="0.66485";
        vector[38]="0.08823";
        vector[39]="0.60311";
        vector[40]="0.93716";
        vector[41]="0.32886";
        vector[42]="0.92052";
        vector[43]="0.95819";
        vector[44]="0.39510";
        vector[45]="0.27699";
        vector[46]="0.92962";
        vector[47]="0.10274";
        vector[48]="0.75867";
        vector[49]="0.85783";
        vector[50]="0.41290";
        vector[51]="0.05870";
        vector[52]="0.82444";
        vector[53]="0.20247";
        vector[54]="0.48460";
        vector[55]="0.60833";
        vector[56]="0.43529";
        vector[57]="0.88722";
        vector[58]="0.94813";
        vector[59]="0.74457";
        vector[60]="0.16894";
        vector[61]="0.59780";
        vector[62]="0.46215";
        vector[63]="0.06831";
        vector[64]="0.35905";
        vector[65]="0.06494";
        vector[66]="0.61773";
        vector[67]="0.12202";
        vector[68]="0.20717";
        vector[69]="0.47619";
        vector[70]="0.63312";
        vector[71]="0.01119";
        vector[72]="0.99005";
        vector[73]="0.81759";
        vector[74]="0.85558";
        vector[75]="0.25983";
        vector[76]="0.06318";
        vector[77]="0.56736";
        vector[78]="0.31900";
        vector[79]="0.90561";
        vector[80]="0.98953";
        vector[81]="0.09958";
        vector[82]="0.15917";
        vector[83]="0.19640";
        vector[84]="0.85244";
        vector[85]="0.03152";
        vector[86]="0.22109";
        vector[87]="0.94205";
        vector[88]="0.82037";
        vector[89]="0.87481";
        vector[90]="0.71857";
        vector[91]="0.92784";
        vector[92]="0.04921";
        vector[93]="0.45197";
        vector[94]="0.15191";
        vector[95]="0.01291";
        vector[96]="0.38384";
        vector[97]="0.66164";
        vector[98]="0.54155";
        vector[99]="0.72848";
        
        

        String texto1= "";
        for (int i=0; i<vector.length; i++){
            texto1+="["+i+"]"+" "+vector[i]+"\n";
        }
        textSerie.setText(texto1);
        
        String texto2= "";
        String texto3= "";
        
        String []cad=new String[2];
        
        char compara='a';
        char compara2='b';
        int compara3=15;
        
        int[] tabla=new int[100];
        int[] pos=new int[10]; 
        for (int i=0;i<10;i++){
            pos[i]=0;
        }
        for (int i=0; i<vector.length; i++){
            texto2=String.valueOf(vector[i]);
            //System.out.println(texto2);
            
            cad=texto2.split("\\."); 
            texto3=cad[1];
            for(int j=0;j<texto3.length();j++){
                compara=texto3.charAt(j);
                for(int k=j+1;k<texto3.length();k++){
                    if(texto3.charAt(j)==texto3.charAt(k)){
                        if(texto3.charAt(k)=='0'){
                            pos[0]++;
                        }else if(texto3.charAt(k)=='1'){
                            pos[1]++;
                        }else if(texto3.charAt(k)=='2'){
                            pos[2]++;
                        }else if(texto3.charAt(k)=='3'){
                            pos[3]++;
                        }else if(texto3.charAt(k)=='4'){
                            pos[4]++;
                        }else if(texto3.charAt(k)=='5'){
                            pos[5]++;
                        }else if(texto3.charAt(k)=='6'){
                            pos[6]++;
                        }else if(texto3.charAt(k)=='7'){
                            pos[7]++;
                        }else if(texto3.charAt(k)=='8'){
                            pos[8]++;
                        }else if(texto3.charAt(k)=='9'){
                            pos[9]++;
                        } 
                    }
                } 
            }
            
            //System.out.println(i+" n0: "+n0+" n1: "+n1+" n2: "+n2+" n3: "+n3+" n4: "+n4+" n5: "+n5+" n6: "+n6+" n7: "+n7+" n8: "+n8+" n9: "+n9);
            int s=0;
            for(int n=0;n<9;n++){
                if(pos[n]==1){
                    s++;
                }else if(pos[n]==3){
                    s=3;
                }
            }
            if(s==0){
                tabla[i]=1;
            }else if(s==1){
                tabla[i]=2;
            }else if(s==2){
                tabla[i]=3;
            }else if(s==3){
                tabla[i]=4;
            }else if(s==6){
                tabla[i]=5;
            }
            for (int z=0;z<10;z++){
            pos[z]=0;
            }
            System.out.println("["+i+"]"+tabla[i]);
            //textBinario.setText("["+i+"]"+tabla[i]);

        }
        int caso1=0;
        int caso2=0;
        int caso3=0;
        int caso4=0;
        int caso5=0;
        String texto4= "";
        for (int i=0; i<tabla.length; i++){
            texto4+="["+i+"]"+" "+tabla[i]+"\n";
            if(tabla[i]==1){
                caso1++;
            }else if(tabla[i]==2){
                caso2++;
            }else if(tabla[i]==3){
                caso3++;
            }else if(tabla[i]==4){
                caso4++;
            }else{
                caso5++;
            }
        }
        textBinario.setText(texto4);
        System.out.println("caso 1:"+caso1+"caso 2:"+caso2+"caso 3:"+caso3+"caso 4:"+caso4+"caso 5:"+caso5);
        double est1=(Math.pow((50.4-(double)caso1),2))/50.4;
        double est2=(Math.pow((43.2-(double)caso2),2))/43.2;
        double est3=(Math.pow((2.7-(double)caso3),2))/2.7;
        double est4=(Math.pow((3.6-(double)caso4),2))/3.6;
        double est5=(Math.pow((0.1-(double)caso5),2))/0.1;
        lblest1.setText("estadistico caso 1: "+est1);
        lblest2.setText("estadistico caso 2: "+est2);
        lblest3.setText("estadistico caso 3: "+est3);
        lblest4.setText("estadistico caso 4: "+est4);
        lblest5.setText("estadistico caso 5: "+est5);
        System.out.println("est 1:"+est1+"est 2:"+est2+"est 3:"+est3+"est 4:"+est4+"est 5:"+est5);
        double sumaEst=est1+est2+est3+est4+est5;
        System.out.println("sumaEst:"+sumaEst);
        lblSumaE.setText("suma estadistico: "+sumaEst);
        if(sumaEst<9.49){
            System.out.println("Se acepta el estadistico:"+sumaEst+", Es menor a 9.49");
            lblCondicion.setText("Se acepta el estadistico:"+sumaEst+", Es menor a 9.49");
        }else{
            System.out.println("Se rechaza el estadistico:"+sumaEst+", Es mayor a 9.49");
            lblCondicion.setText("Se rechaza el estadistico:"+sumaEst+", Es mayor a 9.49");
        }
        
      
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaPocker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaPocker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaPocker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaPocker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PruebaPocker dialog = new PruebaPocker(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAceptacion;
    private javax.swing.JLabel lblCondicion;
    private javax.swing.JLabel lblSumaE;
    private javax.swing.JLabel lblest1;
    private javax.swing.JLabel lblest2;
    private javax.swing.JLabel lblest3;
    private javax.swing.JLabel lblest4;
    private javax.swing.JLabel lblest5;
    private javax.swing.JTextArea textBinario;
    private javax.swing.JTextArea textSerie;
    // End of variables declaration//GEN-END:variables
}
